FROM registry.centos.org/centos/centos:7

MAINTAINER Mohammed Zeeshan Ahmed<moahmed@redhat.com>

RUN yum -y update && yum clean all

ADD fix-permissions.sh install.sh run.sh passwd.template /opt/scripts/

RUN . /opt/scripts/install.sh

USER 1001

EXPOSE 9200 9300

ENTRYPOINT ["/opt/scripts/run.sh"]
CMD ["elastic"]
